# Substitutions
SUBST_CALC_OTP_EXPIRATION = '*CALC_EXPIRED_OTP'
SUBST_CALC_PASSWORD_EXPIRATION = '*CALC_EXPIRED_PASSWORD'
SUBST_GT0 = '*GT0'
SUBST_STRING = '*STRING'
SUBST_GET_FROM_DB = '*GET_FROM_DB'
SUBST_GET_OTP_EXPIRY = '*GET_OTP_EXPIRY'
SUBST_GET_PASSWORD_EXPIRY = '*GET_PASSWORD_EXPIRY'
SUBST_MESSAGE = '*message'

SUCCESS = 'success'
FAIL = 'fail'
DETAIL = 'detail'

PAYLOAD = 'payload'
EXPECT = 'expect'
EXPECT_DB = 'expect_db'

STATUS_CODE = 'status_code'
